### ISSUE TITLE
Removing all files is an anti-pattern in the tests.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/pypi.streamsx.pmml#1]
https://github.com/IBMStreams/pypi.streamsx.pmml/blob/develop/package/streamsx/pmml/tests/test_pmml.py#L28

```
def clean_up():
    run_shell_command_line('rm -rf tk*') 
    run_shell_command_line('rm -f *.sab *.json') 
```

Anti-pattern for these reasons:

 * Removing all files will cause issues once tests are run concurrently (as nose supports). A test should only clean up what it creates.
 * Cleanup is typically done at the end of tests in the `tearDown` test instance method, not at `setUp`.
 * Using a process to remove files seems a bit much, Python can remove files without having to fork a process.

**Comment by markheger** [comment]
clean-up is done in ant script outside, we need to keep these files (no removal at tearDown) because we need to check the generated code.
